project/src/Entity/Utilisateur.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\UtilisateurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=UtilisateurRepository::class)
 * @ApiResource()
 */
class Utilisateur
{
    const ROLE_GUEST ='guest';
    const ROLE_USER  ='user';
    const ROLE_ADMIN ='admin';

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $NomClient;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $PrenomClient;

    /**
     * @ORM\Column(type="text")
     */
    private $Tel;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Role;

    /**
     * @ORM\Column(type="array", nullable=true)
     */
    private $Session = [];

    /**
     * @ORM\OneToMany(targetEntity=AdresseUtilisateur::class, mappedBy="User")
     */
    private $adresseUtilisateurs;

    /**
     * @ORM\OneToMany(targetEntity=Commande::class, mappedBy="Utilisateur")
     */
    private $commandes;

    public function __construct()
    {
        $this->adresseUtilisateurs = new ArrayCollection();
        $this->commandes = new ArrayCollection();
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomClient(): ?string
    {
        return $this->NomClient;
    }

    public function setNomClient(string $NomClient): self
    {
        $this->NomClient = $NomClient;

        return $this;
    }

    public function getPrenomClient(): ?string
    {
        return $this->PrenomClient;
    }

    public function setPrenomClient(string $PrenomClient): self
    {
        $this->PrenomClient = $PrenomClient;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->Tel;
    }

    public function setTel(string $Tel): self
    {
        $this->Tel = $Tel;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->Password;
    }

    public function setPassword(string $Password): self
    {
        $this->Password = $Password;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    public function getRole(): ?string
    {
        return $this->Role;
    }

    public function setRole(string $Role): self
    {
        if(!in_array($Role, array(self::ROLE_GUEST, self::ROLE_USER, self::ROLE_ADMIN))){
            throw new \InvalidArgumentException("Role invalide");
        }

        $this->Role = $Role;
        return $this;
    }

    public function getSession(): ?array
    {
        return $this->Session;
    }

    public function setSession(?array $Session): self
    {
        $this->Session = $Session;

        return $this;
    }

    /**
     * @return Collection|AdresseUtilisateur[]
     */
    public function getAdresseUtilisateurs(): Collection
    {
        return $this->adresseUtilisateurs;
    }

    public function addAdresseUtilisateur(AdresseUtilisateur $adresseUtilisateur): self
    {
        if (!$this->adresseUtilisateurs->contains($adresseUtilisateur)) {
            $this->adresseUtilisateurs[] = $adresseUtilisateur;
            $adresseUtilisateur->setUser($this);
        }

        return $this;
    }

    public function removeAdresseUtilisateur(AdresseUtilisateur $adresseUtilisateur): self
    {
        if ($this->adresseUtilisateurs->removeElement($adresseUtilisateur)) {
            // set the owning side to null (unless already changed)
            if ($adresseUtilisateur->getUser() === $this) {
                $adresseUtilisateur->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Commande[]
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes[] = $commande;
            $commande->setUtilisateur($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        if ($this->commandes->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getUtilisateur() === $this) {
                $commande->setUtilisateur(null);
            }
        }

        return $this;
    }
}

project/templates/template/footer.html.twig
<!-- Footer -->
<footer class="text-center text-lg-start bg-light text-muted" style="height: 100%">
    <!-- Section: Social media -->
    <section
            class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom"
    >
        <!-- Left -->
        <div class="me-5 d-none d-lg-block">
            <span>Rejoignez nous sur nos réseaux sociaux :</span>
        </div>
        <!-- Left -->

        <!-- Right -->
        <div>
            <a href="" class="me-4 text-reset">
                <i class="fab fa-facebook-f"></i>
            </a>
            <a href="" class="me-4 text-reset">
                <i class="fab fa-twitter"></i>
            </a>
            <a href="" class="me-4 text-reset">
                <i class="fab fa-google"></i>
            </a>
            <a href="" class="me-4 text-reset">
                <i class="fab fa-instagram"></i>
            </a>
            <a href="" class="me-4 text-reset">
                <i class="fab fa-linkedin"></i>
            </a>
            <a href="" class="me-4 text-reset">
                <i class="fab fa-github"></i>
            </a>
        </div>
        <!-- Right -->
    </section>
    <!-- Section: Social media -->

    <!-- Section: Links  -->
    <section class="">
        <div class="container text-center text-md-start mt-5">
            <!-- Grid row -->
            <div class="row mt-3">
                <!-- Grid column -->
                <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                    <!-- Content -->
                    <h6 class="text-uppercase fw-bold mb-4">
                        <i class="fas fa-gem me-3"></i>Customize your product shop
                    </h6>
                    <p>
                        N'hésitez pas à nous contacter via nos réseaux sociaux ou par email si vous nécessitez quelconque information.
                    </p>
                </div>
                <!-- Grid column -->
{#
                <!-- Grid column -->
                <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                    <!-- Links -->
                    <h6 class="text-uppercase fw-bold mb-4">
                        Products
                    </h6>
                    <p>
                        <a href="#!" class="text-reset">Angular</a>
                    </p>
                    <p>
                        <a href="#!" class="text-reset">React</a>
                    </p>
                    <p>
                        <a href="#!" class="text-reset">Vue</a>
                    </p>
                    <p>
                        <a href="#!" class="text-reset">Laravel</a>
                    </p>
                </div>
                <!-- Grid column -->

                <!-- Grid column -->
                <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
                    <!-- Links -->
                    <h6 class="text-uppercase fw-bold mb-4">
                        Useful links
                    </h6>
                    <p>
                        <a href="#!" class="text-reset">Pricing</a>
                    </p>
                    <p>
                        <a href="#!" class="text-reset">Settings</a>
                    </p>
                    <p>
                        <a href="#!" class="text-reset">Orders</a>
                    </p>
                    <p>
                        <a href="#!" class="text-reset">Help</a>
                    </p>
                </div>
                <!-- Grid column -->
#}
                <!-- Grid column -->
                <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                    <!-- Links -->
                    <h6 class="text-uppercase fw-bold mb-4">
                        Contact
                    </h6>
                    <p><i class="fas fa-home me-3"></i> Aix-en-Provence, 13100, FR</p>
                    <p>
                        <i class="fas fa-envelope me-3"></i>
                        CYPS@example.com
                    </p>
                    <p><i class="fas fa-phone me-3"></i> + 06 06 06 06 06</p>
                    <p><i class="fas fa-print me-3"></i> + 06 06 06 06 06</p>
                </div>
                <!-- Grid column -->
            </div>
            <!-- Grid row -->
        </div>
    </section>
    <!-- Section: Links  -->

    <!-- Copyright -->
    <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
        © 2021 Copyright: Customize your product shop
    </div>
    <!-- Copyright -->
</footer>
<!-- Footer -->

project/templates/template/navbar.html.twig
<nav class="navbar navbar-expand-lg sticky-top navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Customize your product shop</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/"><i class="fas fa-home"></i> Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{ path('panier') }}"><i class="fas fa-shopping-cart"></i> Panier</a>
                </li>
                {% if(app.session.get('role')=='admin') %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{ path('admin') }}"><i class="fas fa-tools"></i> Administration</a>
                    </li>
                {% endif %}
                {% if(app.session.get('email')==null) %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{ path('account') }}"><i class="fas fa-power-off"></i> Se connecter</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{ path('user') }}"><i class="fas fa-user"></i> Mon compte</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{ path('account_deconnexion') }}"><i class="fas fa-power-off"></i> Se déconnecter</a>
                    </li>
                {% endif %}
            </ul>
            <span class="navbar-text">
      </span>
        </div>
    </div>
</nav>{#
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" href="/"><i class="fas fa-home"></i>Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{{ path('panier') }}"><i
                                class="fas fa-shopping-cart"></i> Panier</a>
                </li>
                {% if(app.session.get('role')=='admin') %}
                    <li class="nav-item">
                        <a class="nav-link active" href="{{ path('admin') }}"><i
                                    class="fas fa-tools"></i> Administration</a>
                    </li>
                {% endif %}
                {% if(app.session.get('email')==null) %}
                    <li class="nav-item">
                        <a class="nav-link active" href="{{ path('account') }}"><i
                                    class="fas fa-power-off"></i> Se connecter</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link active" href="{{ path('user') }}"><i
                                    class="fas fa-user"></i> Mon compte</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{{ path('account_deconnexion') }}"><i
                                    class="fas fa-power-off"></i> Se déconnecter</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>#}