project/src/Entity/Commande.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\CommandeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommandeRepository::class)
 * @ApiResource()
 */
class Commande
{
    const STATUT_EN_ATTENTE ='En attente';
    const STATUT_ARCHIVE  ='Archivé';
    const STATUT_EN_TRAITEMENT ='En cours de traitement';


    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string")
     */
    private $DateCommande;

    /**
     * @ORM\Column(type="string")
     */
    private $DateMinEstime;

    /**
     * @ORM\Column(type="string")
     */
    private $DateMaxEstime;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=0)
     */
    private $PrixTotal;

    /**
     * @ORM\OneToMany(targetEntity=AdresseCommandes::class, mappedBy="Commande")
     */
    private $adresseCommandes;

    /**
     * @ORM\ManyToOne(targetEntity=Utilisateur::class, inversedBy="commandes")
     */
    private $Utilisateur;

    /**
     * @ORM\OneToMany(targetEntity=LigneCommande::class, mappedBy="Commande")
     */
    private $ligneCommandes;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Statut;

    public function __construct()
    {
        $this->Pays = new ArrayCollection();
        $this->adresseCommandes = new ArrayCollection();
        $this->ligneCommandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateCommande(): ?string
    {
        return $this->DateCommande;
    }

    public function setDateCommande(string $DateCommande): self
    {
        $this->DateCommande = $DateCommande;

        return $this;
    }

    public function getDateMinEstime(): ?string
    {
        return $this->DateMinEstime;
    }

    public function setDateMinEstime(string $DateMinEstime): self
    {
        $this->DateMinEstime = $DateMinEstime;

        return $this;
    }

    public function getDateMaxEstime(): ?string
    {
        return $this->DateMaxEstime;
    }

    public function setDateMaxEstime(string $DateMaxEstime): self
    {
        $this->DateMaxEstime = $DateMaxEstime;

        return $this;
    }

    public function getPrixTotal(): ?string
    {
        return $this->PrixTotal;
    }

    public function setPrixTotal(string $PrixTotal): self
    {
        $this->PrixTotal = $PrixTotal;

        return $this;
    }

    /**
     * @return Collection|AdresseCommandes[]
     */
    public function getAdresseCommandes(): Collection
    {
        return $this->adresseCommandes;
    }

    public function addAdresseCommande(AdresseCommandes $adresseCommande): self
    {
        if (!$this->adresseCommandes->contains($adresseCommande)) {
            $this->adresseCommandes[] = $adresseCommande;
            $adresseCommande->setCommande($this);
        }

        return $this;
    }

    public function removeAdresseCommande(AdresseCommandes $adresseCommande): self
    {
        if ($this->adresseCommandes->removeElement($adresseCommande)) {
            // set the owning side to null (unless already changed)
            if ($adresseCommande->getCommande() === $this) {
                $adresseCommande->setCommande(null);
            }
        }

        return $this;
    }

    public function getUtilisateur(): ?Utilisateur
    {
        return $this->Utilisateur;
    }

    public function setUtilisateur(?Utilisateur $Utilisateur): self
    {
        $this->Utilisateur = $Utilisateur;

        return $this;
    }

    /**
     * @return Collection|LigneCommande[]
     */
    public function getLigneCommandes(): Collection
    {
        return $this->ligneCommandes;
    }

    public function addLigneCommande(LigneCommande $ligneCommande): self
    {
        if (!$this->ligneCommandes->contains($ligneCommande)) {
            $this->ligneCommandes[] = $ligneCommande;
            $ligneCommande->setCommande($this);
        }

        return $this;
    }

    public function removeLigneCommande(LigneCommande $ligneCommande): self
    {
        if ($this->ligneCommandes->removeElement($ligneCommande)) {
            // set the owning side to null (unless already changed)
            if ($ligneCommande->getCommande() === $this) {
                $ligneCommande->setCommande(null);
            }
        }

        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->Statut;
    }

    public function setStatut(string $Statut): self
    {
        if(!in_array($Statut, array(self::STATUT_ARCHIVE, self::STATUT_EN_ATTENTE, self::STATUT_EN_TRAITEMENT))){
            throw new \InvalidArgumentException("Statut invalide");
        }

        $this->Statut = $Statut;
        return $this;
    }
}

project/src/Entity/LigneCommande.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\LigneCommandeRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=LigneCommandeRepository::class)
 * @ApiResource()
 */
class LigneCommande
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $Quantite;

    /**
     * @ORM\ManyToOne(targetEntity=Commande::class, inversedBy="ligneCommandes")
     */
    private $Commande;

    /**
     * @ORM\ManyToOne(targetEntity=Declinaison::class, inversedBy="ligneCommandes", cascade={"persist"})
     */
    private $Declinaison;

    /**
     * @ORM\OneToOne(targetEntity=Customization::class, inversedBy="ligneCommande", cascade={"persist", "remove"})
     */
    private $Customization;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $Personnalisations;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getQuantite(): ?int
    {
        return $this->Quantite;
    }

    public function setQuantite(int $Quantite): self
    {
        $this->Quantite = $Quantite;

        return $this;
    }

    public function getCommande(): ?Commande
    {
        return $this->Commande;
    }

    public function setCommande(?Commande $Commande): self
    {
        $this->Commande = $Commande;

        return $this;
    }

    public function getDeclinaison(): ?Declinaison
    {
        return $this->Declinaison;
    }

    public function setDeclinaison(?Declinaison $Declinaison): self
    {
        $this->Declinaison = $Declinaison;

        return $this;
    }

    public function getCustomization(): ?Customization
    {
        return $this->Customization;
    }

    public function setCustomization(?Customization $Customization): self
    {
        $this->Customization = $Customization;

        return $this;
    }

    public function getPersonnalisations(): ?string
    {
        return $this->Personnalisations;
    }

    public function setPersonnalisations(?string $Personnalisations): self
    {
        $this->Personnalisations = $Personnalisations;

        return $this;
    }
}

project/src/Controller/CommandeController.php
<?php

namespace App\Controller;

use App\Entity\AdresseCommandes;
use App\Entity\Commande;
use App\Entity\Customization;
use App\Entity\LigneCommande;
use App\Repository\AdresseUtilisateurRepository;
use App\Repository\CommandeRepository;
use App\Repository\DeclinaisonRepository;
use App\Repository\ProduitRepository;
use App\Repository\UtilisateurRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\Routing\Annotation\Route;

class CommandeController extends AbstractController
{
    /**
     * @Route("/commande/facturation", name="commande_facturation")
     * @param UtilisateurRepository $utilisateurRepository
     * @param Session $session
     * @return Response
     */
    public function facturation(UtilisateurRepository $utilisateurRepository, Session $session): Response
    {
        $UserCtrl= new UserController();
        if(!$UserCtrl->checkUser($session)){
            return $this->redirect('http://localhost/catalogue');
        }

        return $this->render('commande/adrFacturation.html.twig', [
            'adresses' => $utilisateurRepository->findOneByEmail($session->get('email'))->getAdresseUtilisateurs(),
        ]);
    }

    /**
     * @Route("/commande/livraison", name="commande_livraison")
     * @param AdresseUtilisateurRepository $adresseUtilisateurRepository
     * @param UtilisateurRepository $utilisateurRepository
     * @param Session $session
     * @return Response
     */
    public function validerAdrFacturation(AdresseUtilisateurRepository $adresseUtilisateurRepository,UtilisateurRepository $utilisateurRepository, Session $session): Response
    {
        $UserCtrl= new UserController();
        if(!$UserCtrl->checkUser($session)){
            return $this->redirect('http://localhost/catalogue');
        }

        if($_POST['type']=='auto') {
            $infos = $adresseUtilisateurRepository->find($_POST['adr_factu']);
            $session->set('facturation',[
                "pays"=>$infos->getPays(),
                "cp"=>$infos->getCodePostale(),
                "ville"=>$infos->getVille(),
                "rue"=>$infos->getLibelleAdresse(),
                "tel"=>$infos->getTel(),
                "type"=>"facturation"
            ]);
        }
        else if($_POST['type']=='manuel'){
            $session->set('facturation',[
                "pays"=>$_POST['pays'],
                "cp"=>(int)$_POST['cp'],
                "ville"=>$_POST['ville'],
                "rue"=>$_POST['libelle_adr'],
                "tel"=>$_POST['tel'],
                "type"=>"facturation"
            ]);
        }

        return $this->render('commande/adrLivraison.html.twig', [
            'adresses' => $utilisateurRepository->findOneByEmail($session->get('email'))->getAdresseUtilisateurs(),
        ]);
    }
    /**
     * @Route("/commande/payement", name="commande_payement")
     * @param AdresseUtilisateurRepository $adresseUtilisateurRepository
     * @param UtilisateurRepository $utilisateurRepository
     * @param Session $session
     * @return Response
     */
    public function validerAdrLivraison(AdresseUtilisateurRepository $adresseUtilisateurRepository,UtilisateurRepository $utilisateurRepository, Session $session): Response
    {
        $UserCtrl= new UserController();
        if(!$UserCtrl->checkUser($session) || $session->get('facturation') == null){
            return $this->redirect('http://localhost/catalogue');
        }

        if($_POST['type']=='auto') {
            $infos = $adresseUtilisateurRepository->find($_POST['adr_livraison']);
            $session->set('livraison',[
                    "pays"=>$infos->getPays(),
                    "cp"=>$infos->getCodePostale(),
                    "ville"=>$infos->getVille(),
                    "rue"=>$infos->getLibelleAdresse(),
                    "tel"=>$infos->getTel(),
                    "type"=>"livraison"
            ]);
        }
        else if($_POST['type']=='manuel'){
            $session->set('livraison',[
                "pays"=>$_POST['pays'],
                "cp"=>(int)$_POST['cp'],
                "ville"=>$_POST['ville'],
                "rue"=>$_POST['libelle_adr'],
                "tel"=>$_POST['tel'],
                "type"=>"livraison"
            ]);
        }

        return $this->render('commande/payement.html.twig', [
            'adresses' => $utilisateurRepository->findOneByEmail($session->get('email'))->getAdresseUtilisateurs(),
        ]);
    }

    /**
     * @Route("/commande/recapitulatif", name="commande_recapitulation")
     * @param UtilisateurRepository $utilisateurRepository
     * @param Session $session
     * @param EntityManagerInterface $manager
     * @param DeclinaisonRepository $declinaisonRepository
     * @return Response
     */
    public function validerCommande(UtilisateurRepository $utilisateurRepository,
                                    Session $session,
                                    EntityManagerInterface $manager,
                                    DeclinaisonRepository $declinaisonRepository): Response
    {
        $UserCtrl= new UserController();
        if(!$UserCtrl->checkUser($session) || $session->get('facturation') == null || $session->get('livraison') == null){
            return $this->redirect('http://localhost/catalogue');
        }
        $user = $utilisateurRepository->findOneByEmail($session->get('email'));
        setlocale(LC_TIME, 'fra_fra');
        // 2021-05-31 00:00:00
        $dateCommande = date("d/m/Y");
        $dateMin = date("d/m/Y", strtotime('+10 day', mktime(0, 0, 0, date('m'), date('d'), date('Y'))));
        $dateMax = date("d/m/Y", strtotime('+15 day', mktime(0, 0, 0, date('m'), date('d'), date('Y'))));

        $panier = $user->getSession();
        $adresses_f=$session->get('facturation');
        $adresses_l=$session->get('livraison');

        $panierCtrl = new PanierController();
        $livraison = new AdresseCommandes();
        $facturation = new AdresseCommandes();

        $livraison->setCodePostale($adresses_l['cp']);
        $livraison->setLibelleAdresse($adresses_l['rue']);
        $livraison->setTel($adresses_l['tel']);
        $livraison->setPays($adresses_l['pays']);
        $livraison->setVille($adresses_l['ville']);
        $livraison->setType($adresses_l['type']);

        $facturation->setCodePostale($adresses_f['cp']);
        $facturation->setLibelleAdresse($adresses_f['rue']);
        $facturation->setTel($adresses_f['tel']);
        $facturation->setPays($adresses_f['pays']);
        $facturation->setVille($adresses_f['ville']);
        $facturation->setType($adresses_f['type']);


        $commande = new Commande();
        $commande->setUtilisateur($user);
        $commande->setPrixTotal($panier['total']);
        $commande->setDateMinEstime($dateMin);
        $commande->setDateMaxEstime($dateMax);
        $commande->setDateCommande($dateCommande);
        $commande->addAdresseCommande($livraison);
        $commande->addAdresseCommande($facturation);
        $commande->setStatut('En attente');

        $livraison->setCommande($commande);
        $facturation->setCommande($commande);

        $manager->persist($commande);
        $manager->persist($facturation);
        $manager->persist($livraison);
        $manager->flush();

        foreach ($panier as $key => $value){
            if ($key != 'total'){
                foreach ($value as $type => $tab) {
                    if($type == 'base'){
                        $ligne = new LigneCommande();
                        $ligne->setQuantite($value['base']);
                        $ligne->setDeclinaison($declinaisonRepository->find($key));
                        $ligne->setCommande($commande);

                        $produits[$key]['base'] = [
                            "Produit" => $declinaisonRepository->find($key)->getIdProduit(),
                            "Quantity" => $value['base']
                        ];

                        $manager->persist($ligne);
                        $manager->flush();
                    }

                    if($type == 'custom'){
                        foreach ($tab as $it => $item ) {
                            $ligne = new LigneCommande();
                            $custom= new Customization();
                            $custom->setType($item['type']);
                            $custom->setPosition($item['position']);
                            $ligne->setQuantite($item['quantity']);
                            $ligne->setPersonnalisations($item['content']);
                            $ligne->setDeclinaison($declinaisonRepository->find($key));
                            $ligne->setCommande($commande);
                            $ligne->setCustomization($custom);
                            $custom->setLigneCommande($ligne);

                            $produits[$key]['custom'] = [
                                "Produit" => $declinaisonRepository->find($key)->getIdProduit(),
                                "Quantity" => $item['quantity']
                            ];

                            $manager->persist($ligne);
                            $manager->flush();
                        }
                    }
                }
            }
        }

        $session->remove('facturation');
        $session->remove('livraison');
        $session->remove('panier');

        $panierCtrl->updateSessionBDD($user,$session,$manager);

        return $this->render('commande/recap.html.twig', [
            'User'=> $utilisateurRepository->findOneByEmail($session->get('email')),
            'Produits' => $produits,
            'Commande' =>$commande,
            'Adresse'=>[
                'livraison'=>$livraison,
                'facturation'=>$facturation
            ],

project/templates/commande/adrFacturation.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ma commande: Saisir adresse de facturation{% endblock %}

{% block javascripts %}
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"></script>
    <script type="text/javascript" src="../js/adresse.js"></script>
{% endblock %}

{% block body %}
    <div id="form-adr" style="display: flex; align-items: center; flex-direction: column">
        <br><br>
        <h1 id="form-facturation">Adresse de facturation</h1>
        <div id="content">
            <div id="formtitle">
                <div class="manuel btn btn-primary">Renseignez une nouvelle adresse</div>
                <div class="auto btn btn-primary">Choisir dans votre carnet d'adresse</div>
            </div>
            <form method="post" action="{{ path('commande_livraison') }}" id="formmanuel">

                <div class="form-group">
                    <label htmlFor="pays">Pays :</label>
                    <input type="text" name="pays" class="form-control" required>
                </div>
                <div class="form-group">
                    <label htmlFor="cp">Code postale :</label>
                    <input type="text" name="cp" class="form-control" required>
                </div>
                <div class="form-group">
                    <label htmlFor="ville">Ville :</label>
                    <input type="text" name="ville" class="form-control" required>
                </div>
                <div class="form-group">
                    <label htmlFor="libelle_adr">Nom de rue :</label>
                    <input type="text" name="libelle_adr" class="form-control" required>
                </div>
                <div class="form-group">
                    <label htmlFor="tel">Téléphone :</label>
                    <input type="text" name="tel" class="form-control" required>
                </div>
                <input id="type" name="type" type="hidden" value="manuel">
                <div id="btnform">
                    <input class="btn btn-primary" type="submit" value="Suivant">
                </div>
            </form>
            <form method="post" action="{{ path('commande_livraison') }}" id="formauto">
                <label for="adr_factu">Choisir une adresse : </label><br/>
                <select name="adr_factu" id="adr_factu" class="form-select" aria-label="Default select example">
                    {% for adresse in adresses %}
                        <option value="{{ adresse.id }}">{{ adresse.Pays }}, {{ adresse.LibelleAdresse }}, {{ adresse.codepostale }} {{ adresse.ville }}</option>
                    {% endfor %}
                </select>
                <input id="type" name="type" type="hidden" value="auto">
                <div id="btnform">
                    <input class="btn btn-primary" type="submit" value="Suivant">
                </div>
            </form>
        </div>
    </div>
{% endblock %}

project/templates/commande/adrLivraison.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ma commande: Saisir adresse de livraison{% endblock %}
{% block javascripts %}
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"></script>
    <script type="text/javascript" src="../js/adresse.js"></script>
{% endblock %}

{% block body %}
    <div id="form-adr" style="display: flex; align-items: center; flex-direction: column">
        <br><br>
        <h1 id="form-facturation">Adresse de livraison</h1>
        <div id="content">
            <div id="formtitle">
                <div class="manuel btn btn-primary">Renseignez une nouvelle adresse</div>
                <div class="auto btn btn-primary">Choisir dans votre carnet d'adresse</div>
            </div>
            <form method="post" action="{{ path('commande_livraison') }}" id="formmanuel">

                <div class="form-group">
                    <label htmlFor="pays">Pays :</label>
                    <input type="text" name="pays" class="form-control" required>
                </div>
                <div class="form-group">
                    <label htmlFor="cp">Code postale :</label>
                    <input type="text" name="cp" class="form-control"  required>
                </div>
                <div class="form-group">
                    <label htmlFor="ville">Ville :</label>
                    <input type="text" name="ville" class="form-control" required>
                </div>
                <div class="form-group">
                    <label htmlFor="libelle_adr">Nom de rue :</label>
                    <input type="text" name="libelle_adr" class="form-control" required>
                </div>
                <div class="form-group">
                    <label htmlFor="tel">Téléphone :</label>
                    <input type="text" name="tel" class="form-control" required>
                </div>
                <input id="type" name="type" type="hidden" value="manuel">
                <div id="btnform">
                    <input class="btn btn-primary" type="submit" value="Suivant">
                </div>
            </form>
            <form method="post" action="{{ path('commande_payement') }}" id="formauto">
                <label for="le_nom">Choisir une adresse : </label><br/>
                <select name="adr_livraison" id="adr_livraison"  class="form-select" aria-label="Default select example">
                    {% for adresse in adresses %}
                        <option value="{{ adresse.id }}">{{ adresse.Pays }}, {{ adresse.LibelleAdresse }}, {{ adresse.codepostale }} {{ adresse.ville }}</option>
                    {% endfor %}
                </select>
                <input id="type" name="type" type="hidden" value="auto">
                <div id="btnform">
                    <input class="btn btn-primary" type="submit" value="Suivant">
                </div>
            </form>
        </div>
    </div>
{% endblock %}

project/templates/commande/consultation.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commande n°{{ commande.id }}{% endblock %}

{% block body %}
    <div><br><br>
        <div class="d-flex d-flex justify-content-center">
            <div class="alert alert-dark" role="alert" style="width: 25rem;">
                <h3> Dates </h3>
                <div>Commande passée le {{ commande.datecommande }}</div>
                <div>Livraison estimé : entre le {{ commande.dateminestime }} et le {{ commande.datemaxestime }}</div>
                <br>
                <h4> Prix de la commande {{ commande.prixtotal }}€</h4>
            </div>
            <div class="alert alert-dark" role="alert" style="width: 25rem;">
                <h3> Informations livraison </h3>
                {% for livraison in commande.adressecommandes %}
                    {% if livraison.type == "livraison" %}
                        <div> Pays : {{ livraison.pays }}</div>
                        <div> CP : {{ livraison.codepostale }}</div>
                        <div> Ville : {{ livraison.ville }}</div>
                        <div> Adresse : {{ livraison.libelleadresse }}</div>
                        <div> Téléphone : {{ livraison.tel }}</div>
                        <div> Client
                            : {{ commande.utilisateur.prenomclient }} {{ commande.utilisateur.nomclient }}</div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
        <h1 class="display-4 d-flex justify-content-center">Produit(s) commandé(s) :</h1>
        {% for key,produit in produits %}
            <br>
            {% if produit.personnalisations == null %}
                <div class="card" style="width: 30%; margin-right: auto; margin-left: auto">
                    <div class="card-header">Produit {{ key+1 }}: {{ produit.declinaison.produit.libelleproduit }}</div>
                    <div class="card-body">
                        <div>
                            <div>Informations produit</div>
                            <div> Description : {{ produit.declinaison.produit.description }}</div>
                            <div> Déclinaison : {{ produit.declinaison.libelle }}({{ produit.declinaison.coloris }})
                            </div>
                            <div> Prix : {{ produit.declinaison.produit.prix }}</div>
                            <div> Personnalisable : {{ produit.declinaison.produit.personnalisable }}</div>
                            <div> Customisation : non</div>
                            <div> Quantité : {{ produit.quantite }} </div>
                        </div>
                    </div>
                </div>
            {% else %}
                <div class="d-flex">
                    <div class="card" style="width: 20%; margin-left: auto">
                        <div class="card-header">Produit {{ key+1 }}
                            : {{ produit.declinaison.produit.libelleproduit }}</div>
                        <div class="card-body">
                            <div>Informations produit</div>
                            <div> Nom du produit : {{ produit.declinaison.produit.libelleproduit }}</div>
                            <div> Description : {{ produit.declinaison.produit.description }}</div>
                            <div> Déclinaison : {{ produit.declinaison.libelle }}({{ produit.declinaison.coloris }})
                            </div>
                            <div> Prix : {{ produit.declinaison.produit.prix }}</div>
                            <div> Personnalisable : {{ produit.declinaison.produit.personnalisable }}</div>
                            <div> Customisation : oui</div>
                            <div> Quantité : {{ produit.quantite }} </div>
                        </div>
                    </div>
                    <div class="card" style="width: 20%; margin-right: auto;">
                        <div class="card-header">Produit {{ key+1 }}
                            : {{ produit.declinaison.produit.libelleproduit }}</div>
                        <div class="card-body">
                            <h5>Customization :</h5>
                            <div>type : {{ produit.customization.type }}</div>
                            <div>position : {{ produit.customization.position }}</div>
                            {% if produit.customization.type == "txt" %}
                                <div>contenue : {{ produit.personnalisations }}</div>
                            {% else %}
                                <div class="mx-auto card-img">contenue :<img src="data:image/jpeg;base64,{{ produit.personnalisations }}"
                                                          alt="image.jpg"  style="height: 10rem; width: auto"/>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}

project/templates/commande/payement.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ma commande: Payement{% endblock %}

{% block body %}
    <div class="payement d-flex flex-column align-items-center">
        <br>
        <h4>Choisissez un mode de payement :</h4>
        <br>
        <div class="mode-payement d-flex justify-content-center">
            <div>
                <a class="btn btn-primary d-flex align-content-center justify-content-center w-100" href="{{ path('commande_recapitulation') }}"><i class="fab fa-paypal fa-2x"></i> Par paypal </a>
            </div>
            <div style="padding: 20px">
                OU
            </div>
            <div>
                <a class="btn btn-warning d-flex align-content-center justify-content-center w-100" href="{{ path('commande_recapitulation') }}"><i class="fas fa-credit-card fa-2x"></i> Par carte bancaire</a>
            </div>
        </div>
    </div>
{% endblock %}