project/src/Entity/Produit.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\ProduitRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProduitRepository::class)
 * @ApiResource(attributes={"pagination_enabled"=false})
 */
class Produit
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $libelleProduit;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=0)
     */
    private $prix;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $personnalisable;

    /**
     *
     * @ORM\OneToMany(targetEntity=Declinaison::class, mappedBy="produit", cascade={"remove"}, orphanRemoval=true)
     */
    private $declinaisons;

    /**
     * @ORM\OneToMany(targetEntity=Image::class, mappedBy="produit", cascade={"remove"}, orphanRemoval=true)
     */
    private $images;

    /**
     * @ORM\Column(type="boolean")
     */
    private $Disponible;

    public function __construct()
    {
        $this->declinaisons = new ArrayCollection();
        $this->images = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelleProduit(): ?string
    {
        return $this->libelleProduit;
    }

    public function setLibelleProduit(string $libelleProduit): self
    {
        $this->libelleProduit = $libelleProduit;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $Description): self
    {
        $this->description = $Description;

        return $this;
    }

    public function getPrix(): ?string
    {
        return $this->prix;
    }

    public function setPrix(string $Prix): self
    {
        $this->prix = $Prix;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $Image): self
    {
        $this->image = $Image;

        return $this;
    }

    public function getPersonnalisable(): ?string
    {
        return $this->personnalisable;
    }

    public function setPersonnalisable(string $Personnalisable): self
    {
        $this->personnalisable = $Personnalisable;

        return $this;
    }

    /**
     * @return Collection|Declinaison[]
     */
    public function getDeclinaisons(): Collection
    {
        return $this->declinaisons;
    }

    public function addDeclinaison(Declinaison $declinaison): self
    {
        if (!$this->declinaisons->contains($declinaison)) {
            $this->declinaisons[] = $declinaison;
            $declinaison->setProduit($this);
        }

        return $this;
    }

    public function removeDeclinaison(Declinaison $declinaison): self
    {
        if ($this->declinaisons->removeElement($declinaison)) {
            // set the owning side to null (unless already changed)
            if ($declinaison->getProduit() === $this) {
                $declinaison->setProduit(null);
            }
        }

        return $this;
    }
    public function __toString(): string
    {
        return $this->libelleProduit;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setProduit($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getProduit() === $this) {
                $image->setProduit(null);
            }
        }

        return $this;
    }

    public function getDisponible(): ?bool
    {
        return $this->Disponible;
    }

    public function setDisponible(bool $Disponible): self
    {
        $this->Disponible = $Disponible;

        return $this;
    }
}

project/src/Controller/ProduitController.php
<?php


namespace App\Controller;

use App\Entity\Declinaison;
use App\Repository\DeclinaisonRepository;
use App\Repository\ProduitRepository;
use Doctrine\DBAL\Exception;
use phpDocumentor\Reflection\Types\Array_;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;

class ProduitController extends AbstractController
{
    /**
     * @Route("/produit/consulter/{id}", name="produit")
     * @param $id
     * @param ProduitRepository $produitRepository
     * @return mixed
     */
    public function index($id,ProduitRepository $produitRepository)
    {
        try {
            $monProd =$produitRepository->find($id);
            if($monProd==null){
                throw new Exception("Le produit demandé n'existe pas",404);
            }

            return $this->render('produit/produit.html.twig', [
                'produit'=> $monProd,
                'images'=>$monProd->getImages(),
                'declinaisons'=>$monProd->getDeclinaisons()
            ]);
        }
        catch (Exception $e){
            return $this->render('exception/exception.html.twig', [
                'erreur'=> "Erreur n°".$e->getCode().": ".$e->getMessage()
            ]);
        }
    }

    /**
     * @Route("/produit/custom/{id}", name="produit_custom")
     * @param $id
     * @param DeclinaisonRepository $declinaisonRepository
     * @return mixed
     */
    public function custom($id, DeclinaisonRepository $declinaisonRepository)
    {
        return $this->render('produit/custom.html.twig',[
            'produit'=> $declinaisonRepository->find($id)->getIdProduit(),
            'decli'=> $declinaisonRepository->find($id)
        ]);
    }

    /**
     * @Route("/produit/validate/custom/{id}", name="produit_valide_custom")
     * @param $id
     * @param DeclinaisonRepository $declinaisonRepository
     * @return mixed
     */
    public function valideCustom($id, DeclinaisonRepository $declinaisonRepository)
    {
        return $this->redirect('http://localhost/panier');
    }
}

project/templates/produit/custom.html.twig
{% extends 'base.html.twig' %}

{% block title %} Customise ton produit ! {% endblock %}

{% block javascripts %}
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"></script>
    <script type="text/javascript" src="/js/custom.js"></script>
{% endblock %}

{% block body %}
    <div id="form-adr">
        <h1 id="form-facturation">Customise ton produit avec :</h1>

        <h4>Produit selectionné :</h4>
        <div class="produit-custom">
            <img class="img-custom" src="{{ produit.image }}">
            <div>
                <div>{{ produit.LibelleProduit }}</div>
                <div style="color: {{ decli.coloris }}">{{ decli.libelle }}</div>
            </div>
        </div>

        <div id="content">
            <div id="formtitle">
                <div class="type_img"> Une photo</div>
                <div class="type_txt"> Un message</div>
            </div>
            <form method="post" action="{{ path('panier_add_custom', {'id' : decli.id  }) }}" id="formimg" enctype="multipart/form-data">
                <label for="position">Choisir la position : </label><br/>
                <select name="position" id="position">
                    <option value="up"> En haut</option>
                    <option value="down"> En bas</option>
                    <option value="right"> À droite</option>
                    <option value="left"> À gauche</option>
                </select>
                <div class="field">
                    <label for="image">Chosissez votre image (JPG ou PNG | limite : 2Mo) :</label><br/>
                </div>
                <div class="field">
                    <input type="hidden" name="MAX_FILE_SIZE" value="2097152" />
                    <input type="file" name="image" id="icone" accept="image/*"/><br/>
                </div>
                <input id="type" name="type" type="hidden" value="img">
                <div id="btnform">
                    <input class="btn-validate" type="submit" value="Enregistrer">
                </div>
            </form>
            <form method="post" action="{{ path('panier_add_custom', {'id' : decli.id  }) }}" id="formtxt">
                <div>
                    <label for="position">Choisir la position : </label><br/>
                    <select name="position" id="position">
                        <option value="up"> En haut</option>
                        <option value="down"> En bas</option>
                        <option value="right"> À droite</option>
                        <option value="left"> À gauche</option>
                    </select>
                </div>
                <div class="field">
                    <label for="le_nom">Votre message : </label><br/>
                </div>
                <div class="field">
                    <input type="text" id="msg" name="msg" required
                           minlength="1" maxlength="20" size="20">
                </div>
                <input id="type" name="type" type="hidden" value="txt">
                <div id="btnform">
                    <input class="btn-validate" type="submit" value="Enregistrer">
                </div>
            </form>
        </div>
    </div>
{% endblock %}

project/templates/produit/produit.html.twig
{% extends 'base.html.twig' %}

{% block title %} Un Produit {% endblock %}

{% block body %}
    <div>
        <br>
        <div class="card mx-auto" style="width: 60%;">
            <h5 class="card-header">{{ produit.libelleProduit }} </h5>
            <div class="card-body">
                <div id="carouselExampleControls" class="carousel slide w-70 mx-auto" data-bs-ride="carousel">
                    <div class="carousel-inner mx-auto">
                        <div class="carousel-item active">
                            <img src="{{ produit.image }}" class="d-block h-100" style="margin-left: auto; margin-right: auto;" alt="...">
                        </div>
                        {% for image in produit.images %}
                            <div class="carousel-item ">
                                <img src="/images/{{ image.path }}" class="d-block h-100" style="margin-left: auto; margin-right: auto;" alt="...">
                            </div>
                        {% endfor %}
                    </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                    </button>
                </div>
                <p class="card-text">Description : {{ produit.description }}</p>
                <p class="card-text">Personnalisable : {{ produit.personnalisable }}</p>
                <h5 class="card-title">Prix : {{ produit.prix }}€</h5>

                <div class="text-center">
                    {% if produit.disponible == true %}
                        {% for key,decli in declinaisons %}
                            <div class="btn" style="background-color: {{ decli.coloris }}">
                                <div>{{ decli.libelle }}</div>
                                <a class="btn btn-outline-light" href="{{ path('panier_add', {'id' : decli.id }) }}"> Ajouter au panier <i
                                            class='fas fa-cart-plus'></i></a>
                            </div>
                        {% endfor %}
                    {% else %}
                        <h3> Produit indisponible </h3>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}