project/src/Entity/AdresseCommandes.php
<?php

namespace App\Entity;

use App\Repository\AdresseCommandesRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AdresseCommandesRepository::class)
 */
class AdresseCommandes
{
    const TYPE_LIVRAISON ='livraison';
    const TYPE_FACTURATION  ='facturation';

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Commande::class, inversedBy="adresseCommandes")
     */
    private $Commande;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Pays;

    /**
     * @ORM\Column(type="integer")
     */
    private $CodePostale;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Ville;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $LibelleAdresse;

    /**
     * @ORM\Column(type="text")
     */
    private $Tel;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Type;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCommande(): ?Commande
    {
        return $this->Commande;
    }

    public function setCommande(?Commande $Commande): self
    {
        $this->Commande = $Commande;

        return $this;
    }

    public function getPays(): ?string
    {
        return $this->Pays;
    }

    public function setPays(string $Pays): self
    {
        $this->Pays = $Pays;

        return $this;
    }

    public function getCodePostale(): ?int
    {
        return $this->CodePostale;
    }

    public function setCodePostale(int $CodePostale): self
    {
        $this->CodePostale = $CodePostale;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->Ville;
    }

    public function setVille(string $Ville): self
    {
        $this->Ville = $Ville;

        return $this;
    }

    public function getLibelleAdresse(): ?string
    {
        return $this->LibelleAdresse;
    }

    public function setLibelleAdresse(string $LibelleAdresse): self
    {
        $this->LibelleAdresse = $LibelleAdresse;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->Tel;
    }

    public function setTel(string $Tel): self
    {
        $this->Tel = $Tel;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->Type;
    }

    public function setType(string $Type): self
    {
        if(!in_array($Type, array(self::TYPE_FACTURATION, self::TYPE_LIVRAISON))){
            throw new \InvalidArgumentException("Type invalide");
        }

        $this->Type = $Type;
        return $this;
    }
}

project/src/Entity/LigneCommande.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\LigneCommandeRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=LigneCommandeRepository::class)
 * @ApiResource()
 */
class LigneCommande
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $Quantite;

    /**
     * @ORM\ManyToOne(targetEntity=Commande::class, inversedBy="ligneCommandes")
     */
    private $Commande;

    /**
     * @ORM\ManyToOne(targetEntity=Declinaison::class, inversedBy="ligneCommandes", cascade={"persist"})
     */
    private $Declinaison;

    /**
     * @ORM\OneToOne(targetEntity=Customization::class, inversedBy="ligneCommande", cascade={"persist", "remove"})
     */
    private $Customization;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $Personnalisations;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getQuantite(): ?int
    {
        return $this->Quantite;
    }

    public function setQuantite(int $Quantite): self
    {
        $this->Quantite = $Quantite;

        return $this;
    }

    public function getCommande(): ?Commande
    {
        return $this->Commande;
    }

    public function setCommande(?Commande $Commande): self
    {
        $this->Commande = $Commande;

        return $this;
    }

    public function getDeclinaison(): ?Declinaison
    {
        return $this->Declinaison;
    }

    public function setDeclinaison(?Declinaison $Declinaison): self
    {
        $this->Declinaison = $Declinaison;

        return $this;
    }

    public function getCustomization(): ?Customization
    {
        return $this->Customization;
    }

    public function setCustomization(?Customization $Customization): self
    {
        $this->Customization = $Customization;

        return $this;
    }

    public function getPersonnalisations(): ?string
    {
        return $this->Personnalisations;
    }

    public function setPersonnalisations(?string $Personnalisations): self
    {
        $this->Personnalisations = $Personnalisations;

        return $this;
    }
}

project/src/Entity/TVA.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\TVARepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TVARepository::class)
 * @ApiResource()
 */
class TVA
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Pays;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Pourcentage;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPays(): ?string
    {
        return $this->Pays;
    }

    public function setPays(string $Pays): self
    {
        $this->Pays = $Pays;

        return $this;
    }

    public function getPourcentage(): ?string
    {
        return $this->Pourcentage;
    }

    public function setPourcentage(string $Pourcentage): self
    {
        $this->Pourcentage = $Pourcentage;

        return $this;
    }
}

project/src/Entity/Utilisateur.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\UtilisateurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=UtilisateurRepository::class)
 * @ApiResource()
 */
class Utilisateur
{
    const ROLE_GUEST ='guest';
    const ROLE_USER  ='user';
    const ROLE_ADMIN ='admin';

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $NomClient;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $PrenomClient;

    /**
     * @ORM\Column(type="text")
     */
    private $Tel;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Role;

    /**
     * @ORM\Column(type="array", nullable=true)
     */
    private $Session = [];

    /**
     * @ORM\OneToMany(targetEntity=AdresseUtilisateur::class, mappedBy="User")
     */
    private $adresseUtilisateurs;

    /**
     * @ORM\OneToMany(targetEntity=Commande::class, mappedBy="Utilisateur")
     */
    private $commandes;

    public function __construct()
    {
        $this->adresseUtilisateurs = new ArrayCollection();
        $this->commandes = new ArrayCollection();
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomClient(): ?string
    {
        return $this->NomClient;
    }

    public function setNomClient(string $NomClient): self
    {
        $this->NomClient = $NomClient;

        return $this;
    }

    public function getPrenomClient(): ?string
    {
        return $this->PrenomClient;
    }

    public function setPrenomClient(string $PrenomClient): self
    {
        $this->PrenomClient = $PrenomClient;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->Tel;
    }

    public function setTel(string $Tel): self
    {
        $this->Tel = $Tel;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->Password;
    }

    public function setPassword(string $Password): self
    {
        $this->Password = $Password;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    public function getRole(): ?string
    {
        return $this->Role;
    }

    public function setRole(string $Role): self
    {
        if(!in_array($Role, array(self::ROLE_GUEST, self::ROLE_USER, self::ROLE_ADMIN))){
            throw new \InvalidArgumentException("Role invalide");
        }

        $this->Role = $Role;
        return $this;
    }

    public function getSession(): ?array
    {
        return $this->Session;
    }

    public function setSession(?array $Session): self
    {
        $this->Session = $Session;

        return $this;
    }

    /**
     * @return Collection|AdresseUtilisateur[]
     */
    public function getAdresseUtilisateurs(): Collection
    {
        return $this->adresseUtilisateurs;
    }

    public function addAdresseUtilisateur(AdresseUtilisateur $adresseUtilisateur): self
    {
        if (!$this->adresseUtilisateurs->contains($adresseUtilisateur)) {
            $this->adresseUtilisateurs[] = $adresseUtilisateur;
            $adresseUtilisateur->setUser($this);
        }

        return $this;
    }

    public function removeAdresseUtilisateur(AdresseUtilisateur $adresseUtilisateur): self
    {
        if ($this->adresseUtilisateurs->removeElement($adresseUtilisateur)) {
            // set the owning side to null (unless already changed)
            if ($adresseUtilisateur->getUser() === $this) {
                $adresseUtilisateur->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Commande[]
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes[] = $commande;
            $commande->setUtilisateur($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        if ($this->commandes->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getUtilisateur() === $this) {
                $commande->setUtilisateur(null);
            }
        }

        return $this;
    }
}

project/templates/user/adresse.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mes adresses{% endblock %}

{% block body %}
    <div style="width: 70%; margin-right: auto; margin-left: auto">
        <div class="table-responsive-sm">
            {% if adresses | length > 0 %}
                <br><br>
                <table class="table">
                    <thead>
                    <tr class="table-active">
                        <th scope="col">Pays</th>
                        <th scope="col">Code postale</th>
                        <th scope="col">Ville</th>
                        <th scope="col">Nom de rue</th>
                        <th scope="col">Téléphone</th>
                        <th scope="col"> Supprimer</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for adresse in adresses %}
                        <tr>
                            <td>{{ adresse.pays }}</td>
                            <td>{{ adresse.CodePostale }}</td>
                            <td>{{ adresse.ville }}</td>
                            <td>{{ adresse.LibelleAdresse }}</td>
                            <td>{{ adresse.tel }}</td>
                            <td>
                                <a href="{{ path('user_adresse_remove', {'adresse_id' : adresse.id  }) }}" class="btn btn-danger">
                                    <i class="fas fa-trash"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <br><br>
                <p>Votre carnet d'adresse est vide !</p>
                <br><br>
            {% endif %}
            <div id="btnadresse">
                <a href="{{ path('user_modifier', {'donnee' : "Adresse"  }) }}" class="btn btn-success"> <i class="fas fa-plus"></i> Ajouter adresse</a>
            </div>
        </div>
    </div>
{% endblock %}

project/templates/user/commande.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ma commande{% endblock %}

{% block body %}
    <br><br>
    <div class="d-flex justify-content-around">
        {% for Adresse in Adresses %}
        <div class="card">
            <div class="card-header">Adresse {{ Adresse.type }}</div>
            <div class="card-body">
                <div class="card-text">Pays : {{ Adresse.pays }}</div><br>
                <div class="card-text">Adresse : {{ Adresse.libelleAdresse }}, {{ Adresse.codePostale }} {{ Adresse.ville }}</div><br>
                <div class="card-text">Téléphone : {{ Adresse.tel }}</div><br>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="d-flex justify-content-center"></div>
    <div style="width: 70%; margin-right: auto; margin-left: auto" class="table-responsive-sm">
        <br><br>
        <table class="table">
            <thead>
            <tr class="table-active">
                <th scope="col">Produit</th>
                <th scope="col">Déclinaison</th>
                <th scope="col">Personnalisé</th>
                <th scope="col">Prix</th>
                <th scope="col">Quantité</th>
            </tr>
            </thead>
            <tbody>
            {% for Produit in Produits %}
                <tr>
                    <td>{{ Produit.produit.LibelleProduit }}</td>
                    <td>{{ Produit.decli.Libelle }}</td>
                    {% if Produit | length > 4 %}
                        <td> Oui</td>
                    {% else %}
                        <td> Non</td>
                    {% endif %}
                    <td>{{ Produit.produit.prix }}</td>
                    <td>{{ Produit.quantite }}</td>
                </tr>
            {% endfor %}
            </tbody>
            <tfoot>
            <tr>
                <td colspan="3"> Total :</td>
                <td> {{ total }}</td>
            </tr>
            </tfoot>
        </table>
    </div>
{% endblock %}

project/templates/user/commandes.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon historique de commandes{% endblock %}

{% block body %}
    <div class="container">
        <div class="grid ">
            {% if Commandes | length > 0 %}
                {% for Commande in Commandes %}
                    <br><br>
                    <div class="row card">
                            <div class="card-header flex-"> Commande n°{{ Commande.id }}</div>
                            <div class="card-body d-flex justify-content-between">
                                <div class="card-text">Commande passé le : {{ Commande.datecommande }}</div>
                                <a href="{{ path('user_commande', {'commande_id' : Commande.id  }) }}" class="btn btn-outline-primary">
                                    <i class="fas fa-search"></i> Voir commande</a>
                            </div>
                    </div>
                {% endfor %}
            {% else %}
                <h3> Votre historique de commande est vide !</h3>
            {% endif %}
        </div>
    </div>
{% endblock %}

project/templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon compte{% endblock %}

{% block body %}

<div class="example-wrapper">
    <br><br>
    <div class="card w-50 mx-auto">
        <div class="card-header">
            Informations personnelles
        </div>
        <table class="d-flex justify-content-around">
            <tbody>
                <tr>
                    <th>Nom: </th>
                    <td class="personnal-info">{{ user.NomClient }}</td>
                    <td class="personnal-info">
                        <a href="{{ path('user_modifier', {'donnee' : "Nom"  }) }}" class="btn btn-outline-primary">
                            <i class="fas fa-cog"></i> Modifier
                        </a>
                    </td>
                </tr>
                <tr><br></tr>
                <tr>
                    <th>Prénom : </th>
                    <td class="personnal-info">{{ user.PrenomClient }}</td>
                    <td class="personnal-info">
                        <a href="{{ path('user_modifier', {'donnee' : "Prenom"  }) }}" class="btn btn-outline-primary">
                            <i class="fas fa-cog"></i> Modifier
                        </a>
                    </td>
                </tr>
                <tr>
                    <th>Téléphone : </th>
                    <td class="personnal-info">{{ user.Tel }}</td>
                    <td class="personnal-info">
                        <a href="{{ path('user_modifier', {'donnee' : "Tel"  }) }}" class="btn btn-outline-primary">
                            <i class="fas fa-cog"></i> Modifier
                        </a>
                    </td>
                </tr>
                <tr>
                    <th>Email: </th>
                    <td class="personnal-info">{{ user.Email }}</td>
                    <td class="personnal-info">
                        <a href="{{ path('user_modifier', {'donnee' : "Email"  }) }}" class="btn btn-outline-primary">
                            <i class="fas fa-cog"></i> Modifier
                        </a>
                    </td>
                </tr>
                <tr>
                    <th>Password</th>
                    <td class="personnal-info"> </td>
                    <td class="personnal-info">
                        <a href="{{ path('user_modifier', {'donnee' : "Password"  }) }}" class="btn btn-outline-primary">
                            <i class="fas fa-cog"></i> Modifier
                        </a>
                    </td>
                </tr>
            </tbody>
        </table>
        <br>
        <div id="btnadresse" class="mx-auto">
            <a href="{{ path('user_adresse') }}" class="btn btn-primary">
                <i class="fas fa-address-book"></i> Voir mon carnet d'adresse
            </a>
        </div>
        <br>
    </div>
    <br><br>
    <div class="text-center"><a href="{{ path('user_commande_history') }}" class="btn btn-outline-primary">Historique de mes commandes</a></div>
</div>
{% endblock %}